import Foundation

struct FieldInfo {
    let title: String
    let explanation: String
}

func fieldInfo(_ key: String) -> FieldInfo {
    switch key {
    case "frame.darwin.process_info.pid", "frame.darwin.process_info.pname": FieldInfo(title: "Apple PCAPNG process", explanation: "Process label preserved by the capture writer in PCAPNG options. Its scope is this source artifact; it is not independent verification of process identity.")
    case "frame.darwin.process_info.epid", "frame.darwin.process_info.epname": FieldInfo(title: "Apple PCAPNG effective process", explanation: "Effective process label recorded in this source artifact; it can differ when traffic is delegated.")
    case "frame.packet_flags_direction": FieldInfo(title: "PCAPNG direction", explanation: "Capture packet option: 1 means inbound, 2 outbound, and 0 unknown. These direction values agree with Apple PKTAP direction bits.")
    case "frame.number": FieldInfo(title: "Frame number", explanation: "Position of this frame in the source capture.")
    case "frame.time_epoch": FieldInfo(title: "Capture timestamp", explanation: "Original capture time in UTC epoch seconds; the timeline also applies your offset.")
    case "frame.protocols": FieldInfo(title: "Decoded protocol stack", explanation: "Protocol layers recognized in this frame by TShark.")
    case "frame.interface_name": FieldInfo(title: "Capture interface", explanation: "Interface name stored by the capture format, if available.")
    case "frame.len": FieldInfo(title: "Frame length", explanation: "Frame size in bytes on the captured link.")
    case "eth.src": FieldInfo(title: "Ethernet source", explanation: "Observed source link-layer address.")
    case "eth.dst": FieldInfo(title: "Ethernet destination", explanation: "Observed destination link-layer address.")
    case "eth.type": FieldInfo(title: "EtherType", explanation: "Value identifying the payload protocol after Ethernet.")
    case "arp.opcode": FieldInfo(title: "ARP operation", explanation: "ARP request or reply code.")
    case "arp.src.proto_ipv4": FieldInfo(title: "ARP sender IPv4", explanation: "IPv4 address claimed by the ARP sender.")
    case "arp.dst.proto_ipv4": FieldInfo(title: "ARP target IPv4", explanation: "IPv4 address named as the ARP target.")
    case "ip.src", "ipv6.src": FieldInfo(title: "Source IP", explanation: "Observed network-layer source address. It can differ between iPhone and Mac traffic.")
    case "ip.dst", "ipv6.dst": FieldInfo(title: "Destination IP", explanation: "Observed network-layer destination address used for endpoint matching.")
    case "ip.proto", "ipv6.nxt": FieldInfo(title: "IP next protocol", explanation: "Identifier of the transport or extension header following IP.")
    case "icmp.type", "icmpv6.type": FieldInfo(title: "ICMP type", explanation: "Type code for an ICMP control or diagnostic message.")
    case "tcp.srcport", "udp.srcport": FieldInfo(title: "Source port", explanation: "Transport source port observed in this frame; separate hosts commonly use different source ports.")
    case "tcp.dstport", "udp.dstport": FieldInfo(title: "Destination port", explanation: "Transport destination port used for endpoint matching.")
    case "tcp.seq_raw", "tcp.ack_raw": FieldInfo(title: "Raw TCP sequence / acknowledgment", explanation: "Wire value, not capture-relative numbering. Paired with both endpoints, flags and length in the separate direct-peer review; not a payload hash.")
    case "tcp.len", "tcp.flags": FieldInfo(title: "TCP header fingerprint component", explanation: "Decoded TCP payload length or flags. Used with raw sequence/acknowledgment values and endpoints; identical headers alone cannot prove causation.")
    case "log.bootUUID", "log.processImageUUID": FieldInfo(title: "Log identity scope", explanation: "Identifier recorded in the log artifact. Boot and image scope constrain activity navigation but do not establish a process lifetime.")
    case "log.activityIdentifier", "log.parentActivityIdentifier", "log.traceID": FieldInfo(title: "Observed log identifier", explanation: "Source-local logging identifier. Nonzero activity IDs support same-process navigation; no cross-device identifier equivalence or request causation is assumed.")
    case "tcp.flags.ack": FieldInfo(title: "TCP ACK", explanation: "Acknowledgment flag; SYN with ACK is a reply, not a new client initiation.")
    case "dns.response_to": FieldInfo(title: "DNS query frame", explanation: "Decoder-linked query record in this same capture. The resolver checks client, server, transaction ID and question names before citing it.")
    case "dns.flags.rcode": FieldInfo(title: "DNS result code", explanation: "Response status. Only successful, complete answers supply positive address associations; NXDOMAIN invalidates prior names in the observed scope.")
    case "dns.flags.truncated": FieldInfo(title: "DNS truncated response", explanation: "A truncated response is not used to establish a complete address association.")
    case "tcp.flags.syn": FieldInfo(title: "TCP SYN", explanation: "Set on a TCP connection attempt; used to select outbound iPhone candidate frames.")
    case "tcp.stream", "udp.stream": FieldInfo(title: "Decoded stream index", explanation: "TShark's transport conversation index within this capture, used only for within-capture hostname context.")
    case "dns.flags.response": FieldInfo(title: "DNS response flag", explanation: "Distinguishes a DNS answer from a DNS query.")
    case "dns.qry.name": FieldInfo(title: "DNS query name", explanation: "Requested domain name visible in the DNS message; responses repeat the question.")
    case "dns.resp.name": FieldInfo(title: "DNS answer owner", explanation: "Domain name to which a DNS answer record belongs. Multiple owners can make a flattened answer ambiguous.")
    case "dns.resp.ttl": FieldInfo(title: "DNS answer TTL", explanation: "Lifetime in seconds advertised for a DNS answer; used to bound resolution support.")
    case "dns.a": FieldInfo(title: "DNS A answer", explanation: "IPv4 address returned in a DNS answer.")
    case "dns.aaaa": FieldInfo(title: "DNS AAAA answer", explanation: "IPv6 address returned in a DNS answer.")
    case "dns.cname": FieldInfo(title: "DNS CNAME", explanation: "Alias target returned in a DNS answer. Alias chains do not independently establish process attribution.")
    case "dns.id": FieldInfo(title: "DNS transaction ID", explanation: "Message identifier used to pair DNS requests and replies within one flow.")
    case "tls.handshake.type": FieldInfo(title: "TLS handshake type", explanation: "ClientHello, ServerHello, or another visible handshake message type.")
    case "tls.handshake.version": FieldInfo(title: "TLS legacy version", explanation: "Legacy version field; for TLS 1.3, supported_versions is more informative.")
    case "tls.handshake.extensions.supported_version": FieldInfo(title: "TLS supported version", explanation: "Version advertised in the visible ClientHello extension.")
    case "tls.handshake.extensions_server_name": FieldInfo(title: "TLS SNI", explanation: "Visible server name in ClientHello. ECH inner names are not available from ordinary packet capture.")
    case "tls.handshake.extensions_alpn_str": FieldInfo(title: "TLS ALPN", explanation: "Application protocol names advertised in the visible handshake.")
    case "x509af.serialNumber": FieldInfo(title: "Certificate serial", explanation: "Serial number of a certificate visible to the decoder.")
    case "x509af.notBeforeTime": FieldInfo(title: "Certificate valid from", explanation: "Start of the visible certificate validity interval.")
    case "x509af.notAfterTime": FieldInfo(title: "Certificate valid until", explanation: "End of the visible certificate validity interval.")
    case "x509ce.dNSName": FieldInfo(title: "Certificate DNS name", explanation: "DNS Subject Alternative Name from a visible certificate.")
    case "x509sat.uTF8String", "x509sat.printableString": FieldInfo(title: "Certificate name component", explanation: "Visible X.509 distinguished-name text. Its precise role depends on the certificate hierarchy.")
    case "http.request.method": FieldInfo(title: "HTTP/1 method", explanation: "Method in a plaintext HTTP/1 request.")
    case "http.host": FieldInfo(title: "HTTP Host", explanation: "Host header in a plaintext HTTP/1 request.")
    case "http.request.uri": FieldInfo(title: "HTTP request URI", explanation: "Request target in plaintext HTTP/1; may contain sensitive paths or query parameters.")
    case "http.response.code": FieldInfo(title: "HTTP response code", explanation: "Status code in a plaintext HTTP/1 response.")
    case "stun.type": FieldInfo(title: "STUN message type", explanation: "STUN method and class encoded in the packet.")
    case "stun.id": FieldInfo(title: "STUN transaction ID", explanation: "Identifier used to pair STUN requests and replies.")
    case "quic.version": FieldInfo(title: "QUIC version", explanation: "Version from the visible long header; common versions are weak matches alone.")
    case "quic.dcid": FieldInfo(title: "QUIC destination connection ID", explanation: "Visible destination connection ID; IDs may rotate and do not identify a process.")
    case "quic.scid": FieldInfo(title: "QUIC source connection ID", explanation: "Visible source connection ID from a long header.")
    case "quic.long.packet_type", "quic.long.packet_type_v2": FieldInfo(title: "QUIC long-header packet type", explanation: "Distinguishes Initial and other visible QUIC long-header packet types.")
    case "quic.packet_number": FieldInfo(title: "QUIC packet number", explanation: "Decoded packet number when packet protection can be removed.")
    case "quic.token_length": FieldInfo(title: "QUIC token length", explanation: "Length of a visible QUIC Initial token.")
    case "pktap.ifname": FieldInfo(title: "PKTAP interface", explanation: "Interface associated with this captured packet; Mac rvi interfaces are excluded from cross-host candidates.")
    case "pktap.flags": FieldInfo(title: "PKTAP flags", explanation: "Raw Apple PKTAP flags. Direction is interpreted from the direction bits.")
    case "pktap.pid": FieldInfo(title: "PKTAP PID", explanation: "PID attached to this packet in the source artifact. A Mac packet PID cannot identify the process responsible for iPhone traffic.")
    case "pktap.cmdname": FieldInfo(title: "PKTAP process", explanation: "Command name attached to this packet by PKTAP; interpret it within this source artifact.")
    case "pktap.epid": FieldInfo(title: "Effective PKTAP PID", explanation: "Effective process ID, which can differ when traffic is delegated.")
    case "pktap.ecmdname": FieldInfo(title: "Effective PKTAP command", explanation: "Effective command name supplied by PKTAP.")
    case "pktap.svc_class": FieldInfo(title: "PKTAP service class", explanation: "Traffic service class stored in the PKTAP header.")
    case "pktap.iftype": FieldInfo(title: "PKTAP interface type", explanation: "Numeric interface type stored in the PKTAP header.")
    case "pktap.ifunit": FieldInfo(title: "PKTAP interface unit", explanation: "Numeric interface unit stored in the PKTAP header.")
    case "pktap.dlt": FieldInfo(title: "PKTAP DLT", explanation: "Underlying packet link-layer type recorded in PKTAP.")
    case "log.captureLine": FieldInfo(title: "Source-line annotation", explanation: "Generated from the raw stream during fresh normalization. External imports may supply this metadata; it does not determine imported record identity or authenticate provenance.")
    case "log.captureSelection": FieldInfo(title: "Collector selection annotation", explanation: "Fresh normalization records why an event was retained. External imports may supply this metadata. It is not an original OS field or proof of a packet match.")
    case "log.message": FieldInfo(title: "Unified Log message", explanation: "Rendered log event text. Privacy redaction may hide values.")
    case "log.process": FieldInfo(title: "Unified Log process", explanation: "Process image basename associated with the log event.")
    case "log.pid": FieldInfo(title: "Log emitter PID", explanation: "PID scoped to this source device. An iPhone PID must never be joined to a Mac PID; PID reuse remains possible.")
    case "iosLog.rviArtifactID": FieldInfo(title: "Session binding (derived)", explanation: "Added by the importer from the coordinated session manifest. Indicates which RVI artifact was collected for the same selected device; not an identifier emitted by iOS.")
    case "iosLog.timestampConvention": FieldInfo(title: "Timestamp convention (derived)", explanation: "Collection provenance: the external collector was launched with TZ=UTC. This establishes how its naive date text is parsed, not device clock accuracy.")
    case "iosLog.timestamp": FieldInfo(title: "Original collector timestamp", explanation: "Unchanged ISO text from OS trace relay decoder output. Epoch microseconds are derived using the recorded UTC convention; device clock alignment remains unverified.")
    case "iosLog.machTimestamp": FieldInfo(title: "Device monotonic timestamp", explanation: "Unscaled decoder-reported device ticks. No timebase or boot identity has been established, so these cannot be compared with Mac ticks.")
    case "iosLog.procid", "iosLog.threadID": FieldInfo(title: "Device-local identifier", explanation: "Decoder-reported identifier. Not a cross-device operation ID, activity ID or verified process lifetime.")
    case "iosLog.imageUUID": FieldInfo(title: "Image UUID", explanation: "Image identifier from this log source; identifies code, not a unique process incarnation or shared operation.")
    case "log.subsystem": FieldInfo(title: "Unified Log subsystem", explanation: "Logging subsystem assigned by the emitting process.")
    case "log.category": FieldInfo(title: "Unified Log category", explanation: "Logging category assigned by the emitting process.")
    default: FieldInfo(title: key, explanation: "Directly decoded field from this artifact. Check the decoder's field reference for its protocol-specific meaning.")
    }
}
